### PR TITLE
Sound new circular buffer

### PR DESCRIPTION
**Pull request by ARoxdale**
- Rewrite of substantial portions of the sound code.
- Complicated circular buffer logic offloaded to dedicated CBuff data structure.
- Distinction made between audio frames and raw (single channel) audio samples in audio writer calls.

- Include PushSamplesRequestBufs() sound overflow fixes (based on fskipper rates), as well as unix makefile changes
- Tested on SMS PSG sound roms (incl "New Order vs Depeche Mode vs Daft Punk - (Sterbinszky and Coddie Mashup)").

- Let me know if you'd like to see any changes.

### CODE REVIEW

**Comment by ARoxdale** [comment]
Whew. Finally compiles in the VSBuild.

**Comment by ARoxdale** [comment]
Is this pull request too big?
I can try just submitting the sound fixes without the big overhauls to the sound system.

**Comment by ocornut** [comment]
Hello, i haven’t had a chance to look at it so i don’t even know if it’s too big or too anything, sorry. I will.

**Comment by ARoxdale** [comment]
No rush. In your own time. Let me know if it's too big.

**Comment by ARoxdale** [comment]
I'll close this for a more focused Pull request just dealing with the PushSamplesRequestBufs() issue.
The circular buffer was maybe going a bit overboard.

**Comment by ocornut** [comment]
Apologies for sitting idle on this, I'm so sorry.  Feel free to ping me regularly, this is a worthy and important thing.

**Pull request closed without merging**
