### PR TITLE
Updated for Allegro 5.x

### PR DESCRIPTION
**Pull request by MrSVCD**
Updated line 206 so that pkg-config searches for all versions of Allegro 5

### CODE REVIEW

**Comment by ocornut** [comment]
Blindly merged, thank you!

**Comment by sverx** [comment]
BTW I had to revert this change to compile

(I'm on a Linux Mint 18 FWIW)

**Comment by MrSVCD** [comment]
And I had to do this to compile on Ubuntu 18.04 and newer.

**Comment by sverx** [comment]
Interesting. What's the output of
`pkg-config --list-all | grep allegro`
on your system?

**Pull request merged**
